
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install hexo-cli
  - npm install hexo
  - npm install

before_script:

  
script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "nasamars"
  - git config user.email "canghai.yu@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force nasamars:${GH_TOKEN} "https://${GH_REF}" master:master
#  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master

#  - hexo d
#  - git add .
#  - git commit -m "Update docs"
#  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
#   - secure: MFalxtW+f0p11GWqvxjWf8jIiQ4N+alsGHDycJrrQxzknJSAJG+E9sz3Ofnjl7a6m7A9SiXlznHLZAQKxBxiWLPWBdCG5WmpeV7EkJWcZlzPVU3ZkFszZNELSSImPj0itJplvESh/rITCAsTmaHhUn37G6LfSJ/eETGNn/EekUEv/h3eCf3jh2fzKpQj/y48CnsxdBSZrAbSY4LOjrCUDxHFCW0gkOCkLwLZ+6/lWtU8r2PNG3beB41teWXltpF46t0SgNNij03mH99Dotu3mwQrlGz23dcVVVVuc2MrfzXlzuyi977I7HrRt2m3oEpQRJkTr8yeIjay/40WnU/KdTwQoZFWqDKZ8JvNr0ijXMMiMwFPSejY7De0gGsB8DA3bJVyRi77AdgbNADssx6/z0nLzrVQG4BScID5F8EZZfc6SLgDjeQoGkxHRo0PaW3lzhGgqZCAc/LmGOca6B4qWB7Ne1/9wvK9kYqUSrEld4UKc0aSYl7BWqctSJBxDCrL6nfz6h4hlp/e0zofM29o1+C8DVktsFX9YOzAe8f4f6Zu6FqNlpW5v3JNIZuTGl6TuZYtAH6MMQouTC1ftkQpJWkFwJF/nYj14tUBb+vCN04W3GlkFNvBme8Qf6qRgwFnfwxNWDLVfj/kWDrlFvrxaZcwEaz65cH3ZEcjh6m4qUc=
   - GH_REF: github.com/Nasamars/nasamars.github.io.git
#   - GH_TOKEN: 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


#dist: precise