# S: Build Lifecycle
install:
  - npm install

before_script:

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "nasamars"
  - git config user.email "canghai.yu@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:master

#  - hexo d
#  - git add .
#  - git commit -m "Update docs"
#  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/Nasamars/nasamars.github.io.git
